name: Connect to Hashicorp Vault

on:
  push:
    branches: ["vault-trial"]

jobs:
  vault-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          repository: 3um-Group/Github-Vault-Action
          ref: v1.0.2
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # - name: Hashicorp Vault Secrets
      #   uses: 3um-Group/Github-Vault-Action@v1.0.2
      #   with:
      #     CLIENT_ID: ${{ secrets.VAULT_CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.VAULT_TOKEN }}
      #     ORGANIZATION_ID: "2203773f-14a3-405d-bca7-aa95a8c28c97"
      #     PROJECT_ID: "918fb763-cd0e-4d5d-81ea-e6b2c830cf32"
      #     APP_NAME: "preprod-3UM-Website"
      #     SECRET_NAMES: '["preprod_3UMWebsite_Trial"]'

      # - name: Example Step
      #   run: echo "The output value is ${{ steps.hashicorp-vault-secrets.outputs.preprod_3UMWebsite_Trial }}"
